services:
  example_app:
    image: example_app:latest
    container_name: example_app
    env_file:
      - .env
    environment:
      RAILS_ENV: production
      DB_HOSTNAME: mariadb
      DB_DATABASE: example_app
      DB_USERNAME: root
      DB_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    depends_on:
      - mariadb
    expose:
      - '${APP_PORT}'
    networks:
      - mariadb_network
      - caddy_network
    restart: unless-stopped

networks:
  mariadb_network:
    external: true
  caddy_network:
    external: true
