services:
  example_app:
    image: example_app:latest
    container_name: example_app
    env_file:
      - .env
    environment:
      RAILS_ENV: production
    networks:
      - internal_network
    restart: unless-stopped

networks:
  internal_network:
    external: true
