services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mariadb_network
    restart: unless-stopped

volumes:
  mariadb_data:
    name: mariadb_data

networks:
  mariadb_network:
    name: mariadb_network
    driver: bridge
