services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - internal_network
    restart: unless-stopped

volumes:
  mariadb_data:
    name: mariadb_data

networks:
  internal_network:
    external: true
