services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

  example_app:
    image: example_app:latest
    container_name: example_app
    environment:
      RAILS_ENV: production
      DB_HOSTNAME: mariadb
      DB_DATABASE: example_app
      DB_USERNAME: root
      DB_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    depends_on:
      - mariadb
    expose:
      - '3000'
    restart: unless-stopped

volumes:
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config
  mariadb_data:
    name: mariadb_data
