#!/bin/bash
set -euo pipefail

if [ $# -lt 1 ]; then
  echo "Usage: $0 <service_name|domain>"
  exit 1
fi

APP_PORT=80
if [[ "$1" == *.* ]]; then
  DOMAIN="$1"
  SERVICE_NAME="${1%%.*}"
else
  SERVICE_NAME="$1"
  DOMAIN="${SERVICE_NAME}.com"
fi
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TEMPLATES_DIR="$SCRIPT_DIR/../templates"
OUT_DIR="$(pwd)/out"
TARGET_DIR="$OUT_DIR/$SERVICE_NAME"

if [ ! -d "$TEMPLATES_DIR" ]; then
  echo "Error: templates directory not found at $TEMPLATES_DIR"
  exit 1
fi

# Ensure caddy infrastructure
CADDY_DIR="$OUT_DIR/caddy"
if [ ! -d "$CADDY_DIR" ]; then
  echo "Initializing caddy infrastructure..."
  mkdir -p "$CADDY_DIR"
  cp "$TEMPLATES_DIR/caddy/docker-compose.yml" "$CADDY_DIR/docker-compose.yml"
  cat >"$CADDY_DIR/Caddyfile" <<'CADDY_HEADER'
# Caddyfile — generated by vps init
# Add entries manually or re-run init for each service.

CADDY_HEADER
  echo "  Created caddy/docker-compose.yml"
  echo "  Created caddy/Caddyfile"
else
  echo "Caddy infrastructure already exists, skipping."
fi

# Ensure mariadb infrastructure
MARIADB_DIR="$OUT_DIR/mariadb"
if [ ! -d "$MARIADB_DIR" ]; then
  echo "Initializing mariadb infrastructure..."
  mkdir -p "$MARIADB_DIR"
  cp "$TEMPLATES_DIR/mariadb/docker-compose.yml" "$MARIADB_DIR/docker-compose.yml"
  if [ ! -f "$MARIADB_DIR/.env" ]; then
    MARIADB_PASSWORD="$(openssl rand -hex 32)"
    sed "s/^MARIADB_ROOT_PASSWORD=.*/MARIADB_ROOT_PASSWORD=$MARIADB_PASSWORD/" \
      "$TEMPLATES_DIR/mariadb/.env" >"$MARIADB_DIR/.env"
  fi
  echo "  Created mariadb/docker-compose.yml"
  echo "  Created mariadb/.env"
else
  echo "MariaDB infrastructure already exists, skipping."
fi

# Initialize the app service
mkdir -p "$TARGET_DIR"

echo "Cleaning $TARGET_DIR (keeping .env)"
find "$TARGET_DIR" -mindepth 1 ! -name '.env' -exec rm -rf {} +

SECRET_KEY_BASE="$(openssl rand -hex 64)"

echo "Initializing service: $SERVICE_NAME"
echo "  Domain: $DOMAIN"
echo "  Port:   $APP_PORT"

shopt -s dotglob nullglob
for template in "$TEMPLATES_DIR/example_app"/*; do
  filename="$(basename "$template")"
  target="$TARGET_DIR/$filename"

  if [ "$filename" = ".env" ] && [ -f "$target" ]; then
    echo "Keeping existing .env"
    continue
  fi

  sed "s/example_app/$SERVICE_NAME/g" "$template" |
    sed "s/^APP_PORT=.*/APP_PORT=$APP_PORT/" |
    sed "s/^DB_PASSWORD=.*/DB_PASSWORD=$(grep '^MARIADB_ROOT_PASSWORD=' "$MARIADB_DIR/.env" | cut -d'=' -f2)/" |
    sed "s/^DB_DATABASE=.*/DB_DATABASE=$SERVICE_NAME/" |
    sed "s/^SECRET_KEY_BASE=.*/SECRET_KEY_BASE=$SECRET_KEY_BASE/" |
    sed "s/^APP_HOST=.*/APP_HOST=$DOMAIN/" |
    sed "s/^FROM_USER=.*/FROM_USER=no-reply/" >"$target"
  echo "Created $(basename "$target")"
done

# Append Caddy block
CADDYFILE="$CADDY_DIR/Caddyfile"

if grep -q "# $SERVICE_NAME$" "$CADDYFILE" 2>/dev/null; then
  echo "Caddy entry for $SERVICE_NAME already present, skipping."
else
  cat >>"$CADDYFILE" <<CADDY_BLOCK
# $SERVICE_NAME
$DOMAIN {
  reverse_proxy $SERVICE_NAME:$APP_PORT {
    header_up X-Forwarded-Proto https
    header_up X-Forwarded-Host {host}
  }
}

www.$DOMAIN {
  redir https://$DOMAIN{uri} permanent
}

CADDY_BLOCK
  echo "Appended Caddy block for $SERVICE_NAME"
fi

echo "Done."
